def line():
    A=input()
    B=input()
    X1=input()
    X2=input()
    print('Ingrese el coeficiente A:',A)
    print('Ingrese el coeficiente B:',B)
    print('Ingrese el coeficiente X1',X1)
    print("Ingrese el coeficiente X2",X2)
    print('El coeficiente A de su ecuación de la recta es:',str((A/1)))
    print('El coeficiente B de su ecuación de la recta es:',str((B/1)))
    print('El coeficiente X1 de su ecuación de la recta es:',str((X1/1)))
    print('El coeficiente X2 de su ecuación de la recta es:',str((X2/1)))
    print('\t')
    print('Para la siguiente ecuación:\n\tY =',str((A/1))+'X','+',str((B/1)))
    print('\t')
    print('Dados los siguientes puntos:')
    Y1=((A/1)*(X1/1))+(B/1)
    Y2=((A/1)*(X2/1))+(B/1)
    print('\nP1 ('+str((A/1))+',',str(Y1))
    print('\nP2 ('-str((A/1))+',',str(Y2))
    print('\t')
    distancia=((((X2/1)-(X1/1))^2)+((Y2-Y1)^2))^1/2
    print('La distancia entre ellos es:',str(distancia))
    
